services:
  diskover-elasticsearch:
    image: elasticsearch:7.17.10
    container_name: diskover-elasticsearch
    user: "1000:1000"
    environment:
      - discovery.type=single-node
      - xpack.security.enabled=false
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
    volumes:
      - /portainer/Files/AppData/Config/diskover/es_data:/usr/share/elasticsearch/data
    restart: unless-stopped

  diskover:
    image: linuxserver/diskover:latest
    container_name: diskover
    ports:
      - "8884:80"
    volumes:
      - /mnt/MYSMBMOUNT:/data:ro
      - /portainer/Files/AppData/Config/diskover/data:/config
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/Athens
      - ELASTICSEARCH_HOST=diskover-elasticsearch
    depends_on:
      - diskover-elasticsearch
    restart: unless-stopped
