services:
  gocost:
    image: ghcr.io/madalinpopa/gocost-web:${VERSION:-latest}
    ports:
      - "4000:4000"
    environment:
      ALLOWED_HOSTS: ${ALLOWED_HOSTS:-localhost}
      DOMAIN: ${DOMAIN:-localhost}
      CURRENCY: ${CURRENCY:-USD}
      DB_PATH: /app/data/data.sqlite
    volumes:
      - type: volume
        source: gocost_data
        target: /app/data
      - type: volume
        source: gocost_uploads
        target: /app/uploads
    networks:
      - public
    deploy:
      restart_policy:
        condition: on-failure
        delay: 5s
        max_attempts: 3
    healthcheck:
      test:
        [
          "CMD",
          "wget",
          "--quiet",
          "--tries=1",
          "--spider",
          "http://localhost:4000/",
        ]
      interval: 30s
      timeout: 10s
      retries: 3

networks:
  public:
    external: true

volumes:
  gocost_data:
  gocost_uploads:
